version: "3"

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env.template:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/templates:/etc/nginx/templates:rw,cached
    networks:
      - app-networks
    environment:
      - APP_PORT=9000
      - NGINX_PORT=80

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
